import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["CYBERVINCI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["CYBERVINCI_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("CYBERVINCI_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CYBERVINCI_AUTO_HEAP_SNAPSHOT: truthy("CYBERVINCI_AUTO_HEAP_SNAPSHOT"),
  CYBERVINCI_GIT_BASH_PATH: process.env["CYBERVINCI_GIT_BASH_PATH"],
  CYBERVINCI_CONFIG: process.env["CYBERVINCI_CONFIG"],
  CYBERVINCI_CONFIG_CONTENT: process.env["CYBERVINCI_CONFIG_CONTENT"],
  CYBERVINCI_DISABLE_AUTOUPDATE: truthy("CYBERVINCI_DISABLE_AUTOUPDATE"),
  CYBERVINCI_ALWAYS_NOTIFY_UPDATE: truthy("CYBERVINCI_ALWAYS_NOTIFY_UPDATE"),
  CYBERVINCI_DISABLE_PRUNE: truthy("CYBERVINCI_DISABLE_PRUNE"),
  CYBERVINCI_DISABLE_TERMINAL_TITLE: truthy("CYBERVINCI_DISABLE_TERMINAL_TITLE"),
  CYBERVINCI_SHOW_TTFD: truthy("CYBERVINCI_SHOW_TTFD"),
  CYBERVINCI_DISABLE_AUTOCOMPACT: truthy("CYBERVINCI_DISABLE_AUTOCOMPACT"),
  CYBERVINCI_DISABLE_MODELS_FETCH: truthy("CYBERVINCI_DISABLE_MODELS_FETCH"),
  CYBERVINCI_DISABLE_MOUSE: truthy("CYBERVINCI_DISABLE_MOUSE"),
  CYBERVINCI_FAKE_VCS: process.env["CYBERVINCI_FAKE_VCS"],
  CYBERVINCI_SERVER_PASSWORD: process.env["CYBERVINCI_SERVER_PASSWORD"],
  CYBERVINCI_SERVER_USERNAME: process.env["CYBERVINCI_SERVER_USERNAME"],
  CYBERVINCI_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("CYBERVINCI_DISABLE_FFF"),

  // Experimental
  CYBERVINCI_EXPERIMENTAL_FILEWATCHER: Config.boolean("CYBERVINCI_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CYBERVINCI_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CYBERVINCI_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CYBERVINCI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CYBERVINCI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CYBERVINCI_MODELS_URL: process.env["CYBERVINCI_MODELS_URL"],
  CYBERVINCI_MODELS_PATH: process.env["CYBERVINCI_MODELS_PATH"],
  CYBERVINCI_DB: process.env["CYBERVINCI_DB"],

  CYBERVINCI_WORKSPACE_ID: process.env["CYBERVINCI_WORKSPACE_ID"],
  CYBERVINCI_EXPERIMENTAL_WORKSPACES: enabledByExperimental("CYBERVINCI_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get CYBERVINCI_DISABLE_PROJECT_CONFIG() {
    return truthy("CYBERVINCI_DISABLE_PROJECT_CONFIG")
  },
  get CYBERVINCI_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("CYBERVINCI_EXPERIMENTAL_REFERENCES")
  },
  get CYBERVINCI_TUI_CONFIG() {
    return process.env["CYBERVINCI_TUI_CONFIG"]
  },
  get CYBERVINCI_CONFIG_DIR() {
    return process.env["CYBERVINCI_CONFIG_DIR"]
  },
  get CYBERVINCI_PURE() {
    return truthy("CYBERVINCI_PURE")
  },
  get CYBERVINCI_PERMISSION() {
    return process.env["CYBERVINCI_PERMISSION"]
  },
  get CYBERVINCI_PLUGIN_META_FILE() {
    return process.env["CYBERVINCI_PLUGIN_META_FILE"]
  },
  get CYBERVINCI_CLIENT() {
    return process.env["CYBERVINCI_CLIENT"] ?? "cli"
  },
}
